export const IPC_CHANNELS = {
  FOLDER_OPENED: 'folder-opened'
} as const;

export const LAYOUT_CONSTANTS = {
  HORIZONTAL_SPLITTER_SIZE: 4,
  VERTICAL_SPLITTER_SIZE: 4,
  MAIN_AREA_VERTICAL_OFFSET: 4,
  INITIAL_LEFT_WIDTH: 200,
  INITIAL_RIGHT_WIDTH: 200,
  INITIAL_TAB_HEIGHT: 200,
  MIN_SIDE_PERCENT: 18,
  MIN_SIDE_WIDTH_PX: 140,
  MAX_SIDE_WIDTH_PX: 420,
  MIN_CENTER_PERCENT: 45,
  MIN_CENTER_WIDTH_PX: 360,
  MIN_TAB_PANEL_HEIGHT: 150,
  MIN_MAIN_CONTENT_HEIGHT: 200
} as const;
